project_id = "tequit-market"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323

[auth]
enabled = true
site_url = "https://tequit-market.vercel.app"
additional_redirect_urls = ["http://127.0.0.1:3000/auth/callback", "http://localhost:3000/auth/callback", "https://tequit-market.vercel.app/auth/callback"]
enable_signup = true

[auth.email]
enable_signup = true
enable_confirmations = false
double_confirm_changes = false

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]
