import {createHash,randomBytes} from "node:crypto";
import {NextResponse} from "next/server";
import {z} from "zod";
import {getSessionProfile} from "@/lib/auth";
import {createAdminClient} from "@/lib/supabase/admin";
import {APP_URL} from "@/lib/provider-site";

const basics=z.object({name:z.string().trim().min(2).max(120),phone:z.string().trim().regex(/^[\d\s+()-]{8,20}$/),profession:z.string().trim().min(2).max(120),zone:z.string().trim().min(2).max(160),address:z.string().trim().max(240).optional().default(""),source:z.enum(["whatsapp","call","in_person"])});
const service=z.object({canonicalId:z.string().uuid().nullable().optional(),title:z.string().trim().min(3).max(120),description:z.string().trim().max(500).default("")});
const verification=z.object({type:z.enum(["phone","identity","references","visited_by_tequit"]),note:z.string().trim().min(3).max(300)});
const schema=z.discriminatedUnion("action",[
  z.object({action:z.literal("create"),kind:z.enum(["provider","business"]),...basics.shape}),
  z.object({action:z.literal("save"),id:z.string().uuid(),...basics.shape,bio:z.string().trim().max(1200),yearsExperience:z.number().int().min(0).max(80).nullable(),headline:z.string().trim().max(120),areas:z.array(z.string().trim().min(2).max(120)).max(12),services:z.array(service).max(10),verifications:z.array(verification).max(4),consentConfirmed:z.boolean(),consentNote:z.string().trim().max(500),duplicateReviewed:z.boolean(),duplicateNote:z.string().trim().max(500)}),
  z.object({action:z.literal("publish"),id:z.string().uuid()}),
  z.object({action:z.literal("claim_regenerate"),id:z.string().uuid()}),
  z.object({action:z.literal("claim_revoke"),id:z.string().uuid()}),
]);

async function adminSession(){const session=await getSessionProfile();return session?.roles.includes("admin")?session:null}
async function issueClaim(admin:NonNullable<ReturnType<typeof createAdminClient>>,onboarding:{id:string;kind:string;provider_id:string|null;business_id:string|null},createdBy:string){const entityTable=onboarding.kind==="provider"?"provider_profiles":"businesses";const entityId=onboarding.provider_id??onboarding.business_id!;const{data:entity}=await admin.from(entityTable).select("phone,slug").eq("id",entityId).single();const digits=String(entity?.phone??"").replace(/\D/g,"");const token=randomBytes(32).toString("base64url");await admin.from("managed_profile_claims").update({revoked_at:new Date().toISOString()}).eq("onboarding_id",onboarding.id).is("used_at",null).is("revoked_at",null);const{error}=await admin.from("managed_profile_claims").insert({onboarding_id:onboarding.id,token_hash:createHash("sha256").update(token).digest("hex"),phone_last4:digits.slice(-4),expires_at:new Date(Date.now()+30*86400000).toISOString(),created_by:createdBy});if(error)throw error;await admin.from("admin_audit_logs").insert({admin_profile_id:createdBy,action:"assisted_claim_issued",entity_type:onboarding.kind,entity_id:entityId,metadata:{onboarding_id:onboarding.id}});return{claimUrl:`${APP_URL}/reclamar/${token}`,publicUrl:`${APP_URL}/${onboarding.kind==="provider"?"p":"n"}/${entity?.slug}`}}

export async function GET(request:Request){const session=await adminSession();if(!session)return NextResponse.json({error:"No autorizado."},{status:403});const url=new URL(request.url);const q=(url.searchParams.get("q")??"").trim();const kind=url.searchParams.get("kind")==="business"?"business":"provider";if(q.length<3)return NextResponse.json({matches:[]});const admin=createAdminClient()!;const table=kind==="provider"?"provider_profiles":"businesses";const digits=q.replace(/\D/g,"");let query=admin.from(table).select("id,name,phone,slug,status").limit(8);query=digits.length>=8?query.ilike("phone",`%${digits.slice(-8)}%`):query.ilike("name",`%${q}%`);const{data}=await query;return NextResponse.json({matches:data??[]})}

export async function POST(request:Request){const session=await adminSession();if(!session)return NextResponse.json({error:"No autorizado."},{status:403});const parsed=schema.safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:parsed.error.issues[0]?.message??"Datos inválidos."},{status:400});const value=parsed.data;const admin=createAdminClient()!;
  if(value.action==="create"){let entityId:string;let slug:string;if(value.kind==="provider"){const{data:slugValue}=await admin.rpc("unique_provider_slug",{base_name:value.name});slug=slugValue as string;const{data,error}=await admin.from("provider_profiles").insert({owner_profile_id:null,slug,name:value.name,profession:value.profession,phone:value.phone,zone:value.zone,bio:"",status:"draft",is_demo:false,plan:"free"}).select("id").single();if(error||!data)return NextResponse.json({error:"No pudimos crear el borrador."},{status:500});entityId=data.id;await admin.from("provider_site_settings").upsert({provider_id:entityId,headline:`${value.profession} en ${value.zone}`,intro:""})}else{const{data:slugValue}=await admin.rpc("unique_business_slug",{base_name:value.name});slug=slugValue as string;const{data:category}=await admin.from("service_categories").select("id").ilike("name",value.profession).maybeSingle();const{data,error}=await admin.from("businesses").insert({slug,name:value.name,category_id:category?.id,phone:value.phone,zone:value.zone,address:value.address||null,description:"",status:"draft",is_demo:false}).select("id").single();if(error||!data)return NextResponse.json({error:"No pudimos crear el borrador."},{status:500});entityId=data.id}const{data:onboarding,error}=await admin.from("assisted_onboardings").insert({kind:value.kind,provider_id:value.kind==="provider"?entityId:null,business_id:value.kind==="business"?entityId:null,source:value.source,created_by:session.user.id}).select("id").single();if(error||!onboarding)return NextResponse.json({error:"No pudimos iniciar el alta."},{status:500});await admin.from("admin_audit_logs").insert({admin_profile_id:session.user.id,action:"assisted_created",entity_type:value.kind,entity_id:entityId,metadata:{source:value.source}});return NextResponse.json({id:onboarding.id,entityId,slug},{status:201})}
  const{data:onboarding}=await admin.from("assisted_onboardings").select("id,kind,provider_id,business_id,status,consent_confirmed").eq("id",value.id).maybeSingle();if(!onboarding)return NextResponse.json({error:"Alta no encontrada."},{status:404});const entityId=onboarding.provider_id??onboarding.business_id!;
  if(value.action==="save"){if(onboarding.status==="claimed")return NextResponse.json({error:"El propietario ya reclamó este perfil."},{status:409});if(onboarding.kind==="provider"&&value.services.length>5)return NextResponse.json({error:"El plan Free permite hasta cinco servicios."},{status:409});if(onboarding.kind==="provider"){await admin.from("provider_profiles").update({name:value.name,profession:value.profession,phone:value.phone,zone:value.zone,bio:value.bio}).eq("id",entityId);await admin.from("provider_site_settings").upsert({provider_id:entityId,headline:value.headline||`${value.profession} en ${value.zone}`,intro:value.bio,years_experience:value.yearsExperience})}else{const{data:category}=await admin.from("service_categories").select("id").ilike("name",value.profession).maybeSingle();await admin.from("businesses").update({name:value.name,category_id:category?.id,phone:value.phone,zone:value.zone,address:value.address||null,description:value.bio}).eq("id",entityId)}const serviceTable=onboarding.kind==="provider"?"provider_services":"business_services";const ownerColumn=onboarding.kind==="provider"?"provider_id":"business_id";await admin.from(serviceTable).delete().eq(ownerColumn,entityId);if(value.services.length)await admin.from(serviceTable).insert(value.services.map((item)=>({[ownerColumn]:entityId,canonical_service_id:item.canonicalId||null,title:item.title,description:item.description,active:true})));const areaTable=onboarding.kind==="provider"?"provider_service_areas":"business_service_areas";await admin.from(areaTable).delete().eq(onboarding.kind==="provider"?"provider_id":"business_id",entityId);for(const name of value.areas){const{data:area}=await admin.from("service_areas").upsert({name,city:"Tepic",state:"Nayarit"},{onConflict:"name"}).select("id").single();if(area)await admin.from(areaTable).insert({[onboarding.kind==="provider"?"provider_id":"business_id"]:entityId,area_id:area.id})}const verificationTable=onboarding.kind==="provider"?"provider_verifications":"business_verifications";await admin.from(verificationTable).delete().eq(onboarding.kind==="provider"?"provider_id":"business_id",entityId);if(value.verifications.length)await admin.from(verificationTable).insert(value.verifications.map((item)=>({[onboarding.kind==="provider"?"provider_id":"business_id"]:entityId,type:item.type,note:item.note})));await admin.from("assisted_onboardings").update({source:value.source,consent_confirmed:value.consentConfirmed,consent_at:value.consentConfirmed?new Date().toISOString():null,consent_note:value.consentNote,duplicate_reviewed:value.duplicateReviewed,duplicate_note:value.duplicateNote,status:"ready"}).eq("id",value.id);return NextResponse.json({ok:true})}
  if(value.action==="claim_revoke"){await admin.from("managed_profile_claims").update({revoked_at:new Date().toISOString()}).eq("onboarding_id",value.id).is("used_at",null).is("revoked_at",null);await admin.from("admin_audit_logs").insert({admin_profile_id:session.user.id,action:"assisted_claim_revoked",entity_type:onboarding.kind,entity_id:entityId,metadata:{onboarding_id:value.id}});return NextResponse.json({ok:true})}
  if(value.action==="claim_regenerate"){if(onboarding.status==="claimed")return NextResponse.json({error:"Este perfil ya fue reclamado."},{status:409});try{return NextResponse.json(await issueClaim(admin,onboarding,session.user.id))}catch{return NextResponse.json({error:"No pudimos generar el enlace."},{status:500})}}
  let entity:{name:string;phone:string;zone:string;slug:string;bio?:string;description?:string}|null=null;
  if(onboarding.kind==="provider"){const{data}=await admin.from("provider_profiles").select("name,phone,bio,zone,slug").eq("id",entityId).single();entity=data}else{const{data}=await admin.from("businesses").select("name,phone,description,zone,slug").eq("id",entityId).single();entity=data}
  const entityTable=onboarding.kind==="provider"?"provider_profiles":"businesses";const{count:serviceCount}=await admin.from(onboarding.kind==="provider"?"provider_services":"business_services").select("id",{count:"exact",head:true}).eq(onboarding.kind==="provider"?"provider_id":"business_id",entityId).eq("active",true);const bio=onboarding.kind==="provider"?entity?.bio:entity?.description;if(!onboarding.consent_confirmed||!entity?.name||String(entity.phone).replace(/\D/g,"").length<10||!entity.zone||(bio?.trim().length??0)<20||!serviceCount)return NextResponse.json({error:"Completa autorización, contacto, descripción y al menos un servicio."},{status:409});await admin.from(entityTable).update({status:"active"}).eq("id",entityId);await admin.from("assisted_onboardings").update({status:"published",published_at:new Date().toISOString()}).eq("id",value.id);await admin.from("admin_audit_logs").insert({admin_profile_id:session.user.id,action:"assisted_published",entity_type:onboarding.kind,entity_id:entityId,metadata:{onboarding_id:value.id}});try{return NextResponse.json(await issueClaim(admin,onboarding,session.user.id))}catch{return NextResponse.json({publicUrl:`${APP_URL}/${onboarding.kind==="provider"?"p":"n"}/${entity?.slug}`,claimUrl:null})}
}
