import Link from "next/link";
import {Building2,Plus,UserRound} from "lucide-react";
import {AdminShell} from "@/components/admin-shell";
import {AssistedOnboardingActions} from "@/components/assisted-onboarding-actions";
import {DashboardPageHeader,DashboardSection,StatusBadge,dashboardStyles as styles} from "@/components/dashboard-components";
import {requireRole} from "@/lib/auth";
import {createAdminClient} from "@/lib/supabase/admin";

const sourceLabel={whatsapp:"WhatsApp",call:"Llamada",in_person:"En persona"};
export default async function AssistedQueuePage(){await requireRole(["admin"]);const admin=createAdminClient()!;const{data}=await admin.from("assisted_onboardings").select("id,kind,status,source,created_at,updated_at,provider_profiles(name,slug),businesses(name,slug)").order("updated_at",{ascending:false}).limit(100);return <AdminShell><div className={styles.stack}><DashboardPageHeader eyebrow="Captación sin fricción" title="Altas asistidas" description="Crea, retoma y entrega perfiles administrados inicialmente por Tequit." action={<><Link className={styles.primary} href="/admin/prestadores/nuevo"><UserRound size={17}/>Nuevo prestador</Link><Link className={styles.secondary} href="/admin/negocios/nuevo"><Building2 size={17}/>Nuevo negocio</Link></>}/><DashboardSection title="Cola de trabajo" description="Los borradores pueden retomarse; los publicados permiten regenerar o revocar su enlace de reclamo." className={styles.surface}>{data?.length?<table className={styles.table}><thead><tr><th>Perfil</th><th>Origen</th><th>Estado</th><th>Actualizado</th><th>Acciones</th></tr></thead><tbody>{data.map(item=>{const entity=item.kind==="provider"?item.provider_profiles?.[0]:item.businesses?.[0];return <tr key={item.id}><td data-label="Perfil"><strong>{entity?.name??"Sin nombre"}</strong><span className={styles.help}>{item.kind==="provider"?"Prestador":"Negocio"}</span></td><td data-label="Origen">{sourceLabel[item.source as keyof typeof sourceLabel]}</td><td data-label="Estado"><StatusBadge tone={item.status==="draft"?"muted":item.status==="ready"?"warning":"default"}>{item.status}</StatusBadge></td><td data-label="Actualizado">{new Intl.DateTimeFormat("es-MX",{dateStyle:"medium"}).format(new Date(item.updated_at))}</td><td data-label="Acciones"><div className={styles.tableActions}>{item.status!=="claimed"&&<Link className={styles.secondary} href={`/admin/altas/${item.id}`}>{item.status==="published"?"Ver":"Continuar"}</Link>}{entity?.slug&&item.status!=="draft"&&<Link className={styles.ghost} href={`/${item.kind==="provider"?"p":"n"}/${entity.slug}`}>Abrir</Link>}<AssistedOnboardingActions id={item.id} status={item.status}/></div></td></tr>})}</tbody></table>:<div><p className={styles.help}>Todavía no hay altas asistidas.</p><Link className={styles.primary} href="/admin/prestadores/nuevo"><Plus size={17}/>Crear la primera</Link></div>}</DashboardSection></div></AdminShell>}
