import {createHash} from "node:crypto";
import {ShieldCheck} from "lucide-react";
import {ClaimProfileForm} from "@/components/claim-profile-form";
import {SiteContainer} from "@/components/layout-primitives";
import {createAdminClient} from "@/lib/supabase/admin";
import styles from "@/components/identity-redesign.module.css";

export const metadata={title:"Reclamar perfil | Tequit",robots:{index:false,follow:false}};
export default async function ClaimPage({params}:{params:Promise<{token:string}>}){const{token}=await params;const admin=createAdminClient();let valid=false;let name="tu perfil";if(admin&&token.length>=30){const hash=createHash("sha256").update(token).digest("hex");const{data:claim}=await admin.from("managed_profile_claims").select("expires_at,used_at,revoked_at,assisted_onboardings(kind,provider_profiles(name),businesses(name))").eq("token_hash",hash).maybeSingle();valid=Boolean(claim&&!claim.used_at&&!claim.revoked_at&&new Date(claim.expires_at)>new Date());const onboarding=claim?.assisted_onboardings?.[0];name=onboarding?.kind==="provider"?onboarding.provider_profiles?.[0]?.name??name:onboarding?.businesses?.[0]?.name??name}return <main className={styles.authPage}><SiteContainer className={styles.authShell}><div className={styles.authMain}><header className={styles.authHeader}><ShieldCheck size={32}/><p className="eyebrow">Perfil creado por Tequit</p><h1>{valid?`Toma el control de ${name}`:"Este enlace ya no está disponible"}</h1><p>{valid?"Crea una cuenta o inicia sesión. Después podrás editar el perfil, responder solicitudes y consultar estadísticas.":"Puede haber expirado, haber sido revocado o ya haberse utilizado. Solicita un enlace nuevo al equipo de Tequit."}</p></header>{valid&&<div className={styles.formSurface}><ClaimProfileForm token={token}/></div>}</div><aside className={styles.authAside}><ShieldCheck size={30}/><h2>Una entrega segura</h2><p>Verificamos el enlace, tu sesión y los últimos dígitos del teléfono antes de transferir la administración.</p></aside></SiteContainer></main>}
