import {randomUUID} from "node:crypto";
import {NextResponse} from "next/server";
import sharp from "sharp";
import {z} from "zod";
import {getSessionProfile} from "@/lib/auth";
import {createAdminClient} from "@/lib/supabase/admin";

const prepare=z.object({action:z.literal("prepare"),onboardingId:z.string().uuid(),files:z.array(z.object({type:z.enum(["image/jpeg","image/png","image/webp"]),size:z.number().int().positive().max(8*1024*1024)})).min(1).max(10)});
const confirm=z.object({action:z.literal("confirm"),onboardingId:z.string().uuid(),role:z.enum(["avatar","cover","portfolio"]),title:z.string().trim().max(120).default(""),description:z.string().trim().max(500).default(""),paths:z.array(z.string().min(10).max(400)).min(1).max(10)});
const schema=z.discriminatedUnion("action",[prepare,confirm]);

export async function POST(request:Request){const session=await getSessionProfile();if(!session?.roles.includes("admin"))return NextResponse.json({error:"No autorizado."},{status:403});const parsed=schema.safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:"Archivos inválidos."},{status:400});const value=parsed.data;const admin=createAdminClient()!;const{data:onboarding}=await admin.from("assisted_onboardings").select("id,kind,provider_id,business_id").eq("id",value.onboardingId).maybeSingle();if(!onboarding)return NextResponse.json({error:"Alta no encontrada."},{status:404});
  if(value.action==="prepare"){const uploads=[];for(const file of value.files){const extension=file.type==="image/png"?"png":file.type==="image/webp"?"webp":"jpg";const path=`assisted/${value.onboardingId}/${randomUUID()}.${extension}`;const{data,error}=await admin.storage.from("upload-quarantine").createSignedUploadUrl(path);if(!error&&data)uploads.push({path,token:data.token})}return NextResponse.json({uploads})}
  const entityId=onboarding.provider_id??onboarding.business_id!;const bucket=onboarding.kind==="provider"?(value.role==="avatar"?"avatars":"provider-work"):"business-media";let allowedPaths=value.paths;if(value.role==="portfolio"){const mediaTable=onboarding.kind==="provider"?"provider_media":"business_media";const ownerColumn=onboarding.kind==="provider"?"provider_id":"business_id";const{count}=await admin.from(mediaTable).select("id",{count:"exact",head:true}).eq(ownerColumn,entityId);allowedPaths=value.paths.slice(0,Math.max(0,10-(count??0)));if(!allowedPaths.length)return NextResponse.json({error:"Este perfil ya tiene el máximo de 10 trabajos."},{status:409})}const saved=[];for(const path of allowedPaths){if(!path.startsWith(`assisted/${value.onboardingId}/`))continue;const{data:blob}=await admin.storage.from("upload-quarantine").download(path);if(!blob||blob.size>8*1024*1024)continue;try{const input=Buffer.from(await blob.arrayBuffer());const metadata=await sharp(input).metadata();if(!metadata.width||!metadata.height||metadata.width>12000||metadata.height>12000)continue;const output=await sharp(input).rotate().resize({width:2400,height:2400,fit:"inside",withoutEnlargement:true}).webp({quality:84}).toBuffer();const finalPath=`${entityId}/${randomUUID()}.webp`;const{error}=await admin.storage.from(bucket).upload(finalPath,output,{contentType:"image/webp",upsert:false});if(error)continue;if(value.role==="avatar"){if(onboarding.kind==="provider")await admin.from("provider_profiles").update({avatar_path:finalPath}).eq("id",entityId);else await admin.from("businesses").update({logo_path:finalPath}).eq("id",entityId)}else if(value.role==="cover"){if(onboarding.kind==="provider")await admin.from("provider_site_settings").upsert({provider_id:entityId,cover_path:finalPath});else await admin.from("businesses").update({cover_path:finalPath}).eq("id",entityId)}else if(onboarding.kind==="provider"){const{data}=await admin.from("provider_media").insert({provider_id:entityId,storage_path:finalPath,title:value.title||"Trabajo realizado",description:value.description,media_role:"portfolio"}).select("id").single();saved.push({id:data?.id,path:finalPath})}else{const{data}=await admin.from("business_media").insert({business_id:entityId,storage_path:finalPath,title:value.title||"Trabajo realizado"}).select("id").single();saved.push({id:data?.id,path:finalPath})}if(value.role!=="portfolio")saved.push({path:finalPath})}finally{await admin.storage.from("upload-quarantine").remove([path])}}
  return NextResponse.json({saved});
}
