import Link from "next/link";
import { BadgeCheck, BrickWall, Droplets, Grid2X2, MapPin, PaintRoller, Search, Snowflake, Sparkles, WashingMachine, Zap } from "lucide-react";
import { SearchBar } from "@/components/search-bar";
import { BusinessCard, ProviderCard } from "@/components/cards";
import { businesses, categories, providers, services } from "@/lib/demo-data";

const icons = { BrickWall, Droplets, Zap, Grid2X2, WashingMachine, PaintRoller, Snowflake, Sparkles };
export default function HomePage(){return <main><section className="hero"><div className="container"><div className="hero-content"><p className="eyebrow"><MapPin size={14} style={{display:"inline"}}/> Tepic, Nayarit</p><h1>Encuentra quién le sabe.</h1><p className="hero-copy">Personas y negocios que pueden hacer el trabajo que necesitas. Revisa sus trabajos, reputación y verificaciones; contáctalos directamente.</p><SearchBar/><div className="hero-proof"><span><BadgeCheck size={17}/>Perfiles con señales de confianza</span><span><Search size={17}/>Busca como lo dirías normalmente</span></div></div></div></section>
<section className="section"><div className="container"><div className="section-head"><div><p className="eyebrow">Accesos rápidos</p><h2>¿Qué hay que resolver?</h2></div><Link className="btn btn-secondary" href="/buscar">Ver todos los servicios</Link></div><div className="category-row">{categories.map(c=>{const Icon=icons[c.icon as keyof typeof icons];return <Link key={c.slug} className="category-link" href={`/servicios/${c.slug}`}><span className="category-icon"><Icon size={22}/></span><strong>{c.name}</strong></Link>})}</div></div></section>
<section className="section" style={{background:"var(--cream)"}}><div className="container"><div className="section-head"><div><p className="eyebrow">Servicios más buscados</p><h2>Lo que Tepic está buscando</h2></div></div><div className="filters">{[services.plomeria,services.piso,services.concreto,services.lavadoras,services.minisplit,services.pintura].map(s=><Link className="chip" key={s.id} href={`/buscar?q=${encodeURIComponent(s.name)}`}>{s.name}</Link>)}</div></div></section>
<section className="section"><div className="container"><div className="section-head"><div><p className="eyebrow">Confianza local</p><h2>Prestadores verificados</h2></div><Link className="btn btn-secondary" href="/buscar?verified=true">Explorar perfiles</Link></div><div className="provider-grid">{providers.filter(p=>p.featured||p.rating>=4.9).slice(0,3).map(p=><ProviderCard key={p.id} provider={p}/>)}</div></div></section>
<section className="section" style={{borderTop:"1px solid var(--line)"}}><div className="container"><div className="section-head"><div><p className="eyebrow">También en Tequit</p><h2>Negocios locales que resuelven</h2></div><Link className="btn btn-secondary" href="/negocios">Ver negocios</Link></div><div className="business-grid">{businesses.slice(0,3).map(b=><BusinessCard key={b.id} business={b}/>)}</div></div></section>
<section className="section"><div className="container" style={{background:"var(--forest)",color:"white",borderRadius:28,padding:"clamp(28px,6vw,70px)"}}><p className="eyebrow" style={{color:"#f1bca7"}}>Para prestadores</p><h2 style={{maxWidth:650}}>Haz que te encuentren cuando alguien necesite lo que tú sabes hacer.</h2><p style={{color:"#d2dfd7",maxWidth:560}}>Crea tu perfil gratis, muestra tus trabajos y recibe solicitudes sin comisiones.</p><Link className="btn btn-primary" href="/registro">Crear mi perfil</Link></div></section></main>}
