"use client";

import Link from "next/link";
import {usePathname} from "next/navigation";
import {useEffect,useRef,useState} from "react";
import {Building2,ExternalLink,LayoutDashboard,Rows3,UserRound,X} from "lucide-react";
import {BrandLogo} from "@/components/brand-logo";
import {LogoutButton} from "@/components/logout-button";
import {dashboardStyles as styles} from "@/components/dashboard-components";
import {cn} from "@/lib/cn";

const navigation=[["/admin",LayoutDashboard,"Resumen"],["/admin/altas",Rows3,"Altas asistidas"],["/admin/prestadores/nuevo",UserRound,"Nuevo prestador"],["/admin/negocios/nuevo",Building2,"Nuevo negocio"]] as const;

function AdminNavigation({onNavigate}:{onNavigate?:()=>void}){const pathname=usePathname();return <nav className={styles.adminDrawerNav} aria-label="Administración">{navigation.map(([href,Icon,label])=>{const active=href==="/admin"?pathname===href:pathname.startsWith(href);return <Link className={cn(styles.adminDrawerLink,active&&styles.adminDrawerLinkActive)} href={href} key={href} aria-current={active?"page":undefined} onClick={onNavigate}><Icon size={19} aria-hidden/>{label}</Link>})}<Link className={styles.adminDrawerLink} href="/" onClick={onNavigate}><ExternalLink size={19} aria-hidden/>Ver sitio público</Link></nav>}
function AdminBottomNavigation(){const pathname=usePathname();return <nav className={styles.adminBottomNav} aria-label="Navegación administrativa">{navigation.map(([href,Icon,label])=>{const active=href==="/admin"?pathname===href:pathname.startsWith(href);return <Link href={href} key={href} className={cn(active&&styles.adminBottomActive)} aria-current={active?"page":undefined}><Icon aria-hidden/><span>{label.replace("Nuevo ","")}</span></Link>})}</nav>}

export function AdminShell({children}:{children:React.ReactNode}){const[open,setOpen]=useState(false);const triggerRef=useRef<HTMLButtonElement>(null);const drawerRef=useRef<HTMLElement>(null);useEffect(()=>{if(!open)return;const previous=document.body.style.overflow;const trigger=triggerRef.current;document.body.style.overflow="hidden";drawerRef.current?.querySelector<HTMLElement>("a,button")?.focus();const close=(event:KeyboardEvent)=>event.key==="Escape"&&setOpen(false);document.addEventListener("keydown",close);return()=>{document.body.style.overflow=previous;document.removeEventListener("keydown",close);trigger?.focus()}},[open]);return <div className={styles.adminFrame}><header className={styles.adminHeader}><div className={styles.adminHeaderInner}><button ref={triggerRef} className={styles.adminProfileTrigger} type="button" onClick={()=>setOpen(true)} aria-label="Abrir menú administrativo" aria-expanded={open}><span className={styles.adminAvatar} aria-hidden>AT</span><span><small>Administración</small><strong>Tequit</strong></span></button><Link className={styles.adminBrand} href="/admin" aria-label="Administración Tequit"><BrandLogo variant="horizontal" priority/><span className={styles.adminContext}>Administración Tequit</span></Link><nav className={styles.adminNav} aria-label="Administración"><Link href="/admin">Resumen</Link><Link href="/admin/altas">Altas asistidas</Link><Link href="/admin/prestadores/nuevo">Nuevo prestador</Link><Link href="/admin/negocios/nuevo">Nuevo negocio</Link><Link href="/"><ExternalLink size={16}/>Ver sitio</Link><LogoutButton className={styles.ghost}/></nav></div></header>{open&&<div className={styles.drawerOverlay} role="presentation" onMouseDown={event=>event.target===event.currentTarget&&setOpen(false)}><aside ref={drawerRef} className={styles.adminDrawer} role="dialog" aria-modal="true" aria-label="Menú administrativo"><div className={styles.drawerTop}><div className={styles.adminDrawerIdentity}><span className={styles.adminAvatar} aria-hidden>AT</span><div><strong>Administración Tequit</strong><span>Operación y altas</span></div></div><button type="button" onClick={()=>setOpen(false)} aria-label="Cerrar menú"><X aria-hidden/></button></div><AdminNavigation onNavigate={()=>setOpen(false)}/><LogoutButton className={cn(styles.adminDrawerLink,styles.logout)}/></aside></div>}<main className={styles.adminContent}>{children}</main><AdminBottomNavigation/></div>}
