"use client";

import Link from "next/link";
import {useMemo,useState} from "react";
import {Check,Copy,ExternalLink,ImagePlus,LoaderCircle} from "lucide-react";
import {createClient} from "@/lib/supabase/client";
import {dashboardStyles} from "@/components/dashboard-components";
import styles from "@/components/assisted-onboarding.module.css";

export type AssistedService={canonicalId:string|null;title:string;description:string};
export type AssistedVerification={type:"phone"|"identity"|"references"|"visited_by_tequit";note:string};
export type AssistedInitial={id:string;entityId:string;slug:string;status:string;name:string;phone:string;profession:string;zone:string;address:string;source:"whatsapp"|"call"|"in_person";bio:string;headline:string;yearsExperience:number|null;areas:string[];services:AssistedService[];verifications:AssistedVerification[];consentConfirmed:boolean;consentNote:string;duplicateReviewed:boolean;duplicateNote:string};

type Props={kind:"provider"|"business";canonicalServices:{id:string;name:string;category:string}[];initial?:AssistedInitial};
const steps=["Datos básicos","Servicios","Fotos","Perfil","Verificación","Confirmar"];
const verificationLabels={phone:"WhatsApp de contacto revisado",identity:"Identidad revisada",references:"Referencias revisadas",visited_by_tequit:"Visitado por Tequit"};

export function AssistedOnboardingWizard({kind,canonicalServices,initial}:Props){
  const [step,setStep]=useState(initial?1:0);const [id,setId]=useState(initial?.id??"");
  const [name,setName]=useState(initial?.name??"");const [phone,setPhone]=useState(initial?.phone??"");const [profession,setProfession]=useState(initial?.profession??"");const [zone,setZone]=useState(initial?.zone??"Tepic, Nayarit");const [address,setAddress]=useState(initial?.address??"");const [source,setSource]=useState<Props["kind"] extends never?never:"whatsapp"|"call"|"in_person">(initial?.source??"whatsapp");
  const [bio,setBio]=useState(initial?.bio??"");const [headline,setHeadline]=useState(initial?.headline??"");const [yearsExperience,setYearsExperience]=useState<number|null>(initial?.yearsExperience??null);const [areasText,setAreasText]=useState((initial?.areas??["Tepic"]).join("\n"));
  const [services,setServices]=useState<AssistedService[]>(initial?.services??[]);const [verifications,setVerifications]=useState<AssistedVerification[]>(initial?.verifications??[]);const [consentConfirmed,setConsentConfirmed]=useState(initial?.consentConfirmed??false);const [consentNote,setConsentNote]=useState(initial?.consentNote??"");const [duplicateReviewed,setDuplicateReviewed]=useState(initial?.duplicateReviewed??false);const [duplicateNote,setDuplicateNote]=useState(initial?.duplicateNote??"");
  const [matches,setMatches]=useState<{id:string;name:string;phone:string;slug:string;status:string}[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [notice,setNotice]=useState("");const [result,setResult]=useState<{publicUrl:string;claimUrl:string|null}|null>(null);const [uploads,setUploads]=useState(0);
  const maxServices=kind==="provider"?5:10;const title=kind==="provider"?"prestador":"negocio";const areas=useMemo(()=>areasText.split(/[\n,]/).map(v=>v.trim()).filter(Boolean),[areasText]);

  async function api(body:unknown){const response=await fetch("/api/admin/onboardings",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw new Error(data.error||"No pudimos guardar los cambios.");return data}
  async function checkDuplicates(){if(name.trim().length<3&&phone.replace(/\D/g,"").length<8)return;const query=phone.replace(/\D/g,"").length>=8?phone:name;const response=await fetch(`/api/admin/onboardings?kind=${kind}&q=${encodeURIComponent(query)}`);const data=await response.json();setMatches(data.matches??[])}
  async function ensureDraft(){if(id)return id;const data=await api({action:"create",kind,name,phone,profession,zone,address,source});setId(data.id);return data.id as string}
  async function save(showNotice=false){setError("");setBusy(true);try{const onboardingId=await ensureDraft();await api({action:"save",id:onboardingId,name,phone,profession,zone,address,source,bio,headline,yearsExperience,areas,services,verifications,consentConfirmed,consentNote,duplicateReviewed,duplicateNote});if(showNotice)setNotice("Borrador guardado.");return true}catch(value){setError(value instanceof Error?value.message:"No pudimos guardar.");return false}finally{setBusy(false)}}
  async function next(){setNotice("");if(step===0){if(name.trim().length<2||phone.replace(/\D/g,"").length<8||profession.trim().length<2||zone.trim().length<2){setError("Completa nombre, teléfono, actividad y zona.");return}await checkDuplicates()}if(step===1&&!services.length){setError("Selecciona al menos un servicio.");return}if(step===4&&verifications.some(item=>item.note.trim().length<3)){setError("Agrega una nota breve a cada verificación.");return}if(!await save())return;setError("");setStep(value=>Math.min(5,value+1))}
  function toggleService(item:{id:string;name:string}){setError("");const exists=services.some(service=>service.canonicalId===item.id);if(exists)setServices(value=>value.filter(service=>service.canonicalId!==item.id));else if(services.length<maxServices)setServices(value=>[...value,{canonicalId:item.id,title:item.name,description:""}]);else setError(`Puedes agregar hasta ${maxServices} servicios.`)}
  function toggleVerification(type:AssistedVerification["type"]){setVerifications(value=>value.some(item=>item.type===type)?value.filter(item=>item.type!==type):[...value,{type,note:"Confirmado durante el alta asistida"}])}
  async function upload(files:FileList|null,role:"avatar"|"cover"|"portfolio"){if(!files?.length)return;setBusy(true);setError("");try{const onboardingId=await ensureDraft();const selected=Array.from(files).slice(0,10);const prep=await fetch("/api/admin/onboardings/media",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"prepare",onboardingId,files:selected.map(file=>({type:file.type,size:file.size}))})});const prepData=await prep.json();if(!prep.ok)throw new Error(prepData.error);const supabase=createClient();const paths:string[]=[];for(let index=0;index<prepData.uploads.length;index++){const target=prepData.uploads[index];const file=selected[index];const {error:uploadError}=await supabase.storage.from("upload-quarantine").uploadToSignedUrl(target.path,target.token,file,{contentType:file.type});if(uploadError)throw uploadError;paths.push(target.path)}const confirm=await fetch("/api/admin/onboardings/media",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"confirm",onboardingId,role,title:"Trabajo realizado",description:"",paths})});const confirmData=await confirm.json();if(!confirm.ok)throw new Error(confirmData.error);setUploads(value=>value+(confirmData.saved?.length??0));setNotice("Fotos procesadas y guardadas.")}catch(value){setError(value instanceof Error?value.message:"No pudimos subir las fotos.")}finally{setBusy(false)}}
  async function publish(){if(!consentConfirmed){setError("Confirma la autorización antes de publicar.");return}if(matches.length&&!duplicateReviewed){setError("Confirma que revisaste los posibles duplicados.");return}if(!await save())return;setBusy(true);try{const data=await api({action:"publish",id});setResult(data)}catch(value){setError(value instanceof Error?value.message:"No pudimos publicar.")}finally{setBusy(false)}}
  async function copy(value:string){await navigator.clipboard.writeText(value);setNotice("Enlace copiado.")}

  if(result)return <div className={styles.result}><Check size={30}/><h2>{name} ya está publicado</h2><p>Comparte el sitio ahora y guarda el enlace privado de reclamo. Por seguridad, Tequit no conserva el token visible.</p><div className={styles.resultActions}><a className={dashboardStyles.secondary} href={result.publicUrl} target="_blank" rel="noreferrer"><ExternalLink size={17}/>Abrir sitio</a><button className={dashboardStyles.secondary} onClick={()=>copy(result.publicUrl)}><Copy size={17}/>Copiar sitio</button>{result.claimUrl&&<button className={dashboardStyles.secondary} onClick={()=>copy(result.claimUrl!)}><Copy size={17}/>Copiar reclamo</button>}</div>{result.claimUrl&&<code>{result.claimUrl}</code>}<Link href="/admin/altas" className={dashboardStyles.ghost}>Volver a altas</Link></div>;
  return <div className={styles.shell}><div className={styles.progress} aria-label={`Paso ${step+1} de ${steps.length}`}>{steps.map((label,index)=><span className={index<=step?styles.done:""} title={label} key={label}/>)}</div><div className={styles.layout}><section className={styles.panel}><header className={styles.stepHead}><div><p>Paso {step+1} de {steps.length}</p><h1>{steps[step]}</h1><p>Alta asistida de {title}. El borrador se conserva al avanzar.</p></div>{busy&&<LoaderCircle className="spin" aria-label="Guardando"/>}</header>{error&&<p className={styles.error} role="alert">{error}</p>}{notice&&<p className={styles.status}>{notice}</p>}
    {step===0&&<div className={`${styles.form} ${styles.grid}`}><Field label="Nombre"><input value={name} onChange={e=>setName(e.target.value)} onBlur={checkDuplicates}/></Field><Field label="WhatsApp"><input inputMode="tel" value={phone} onChange={e=>setPhone(e.target.value)} onBlur={checkDuplicates} placeholder="311 123 4567"/></Field><Field label={kind==="provider"?"Oficio o profesión":"Categoría principal"}><input value={profession} onChange={e=>setProfession(e.target.value)} placeholder="Ej. Albañil"/></Field><Field label="Zona"><input value={zone} onChange={e=>setZone(e.target.value)}/></Field>{kind==="business"&&<Field label="Dirección" full><input value={address} onChange={e=>setAddress(e.target.value)}/></Field>}<div className={`${styles.field} ${styles.full}`}><span>Origen del consentimiento</span><div className={styles.choice}>{([['whatsapp','WhatsApp'],['call','Llamada'],['in_person','En persona']] as const).map(([value,label])=><button type="button" className={source===value?styles.selected:""} onClick={()=>setSource(value)} key={value}>{label}</button>)}</div></div>{matches.length>0&&<div className={`${styles.matches} ${styles.full}`}><strong>Posibles duplicados</strong>{matches.map(match=><a href={`/${kind==="provider"?"p":"n"}/${match.slug}`} target="_blank" rel="noreferrer" key={match.id}>{match.name} · {match.phone} · {match.status}</a>)}</div>}</div>}
    {step===1&&<div className={styles.form}><p className={styles.notice}>Selecciona hasta {maxServices}. Después agrega una descripción concreta para que la ficha sea útil y posicionable.</p><div className={styles.serviceList}>{canonicalServices.map(item=>{const selected=services.some(service=>service.canonicalId===item.id);return <label className={styles.service} key={item.id}><input type="checkbox" checked={selected} onChange={()=>toggleService(item)}/><span><strong>{item.name}</strong><small>{item.category}</small></span></label>})}</div>{services.map((service,index)=><Field label={`Descripción de ${service.title}`} key={service.canonicalId??index}><textarea value={service.description} onChange={e=>setServices(value=>value.map((item,i)=>i===index?{...item,description:e.target.value}:item))} maxLength={500}/></Field>)}</div>}
    {step===2&&<div className={styles.form}><p className={styles.notice}>Puedes tomar las fotos desde el celular o seleccionar las que recibiste por WhatsApp. Se convierten a WebP antes de publicarse.</p><Upload label={kind==="provider"?"Foto de perfil":"Logo del negocio"} onFiles={files=>upload(files,"avatar")}/><Upload label="Portada" onFiles={files=>upload(files,"cover")}/><Upload label="Trabajos realizados (hasta 10)" multiple onFiles={files=>upload(files,"portfolio")}/>{uploads>0&&<p className={styles.status}>{uploads} archivo(s) guardado(s) en esta sesión.</p>}</div>}
    {step===3&&<div className={`${styles.form} ${styles.grid}`}><Field label="Presentación" full><textarea value={bio} onChange={e=>setBio(e.target.value)} maxLength={1200} placeholder="Qué hace, cómo trabaja y qué puede esperar el cliente."/></Field>{kind==="provider"&&<><Field label="Frase comercial"><input value={headline} onChange={e=>setHeadline(e.target.value)} maxLength={120}/></Field><Field label="Años de experiencia"><input type="number" min="0" max="80" value={yearsExperience??""} onChange={e=>setYearsExperience(e.target.value===""?null:Number(e.target.value))}/></Field></>}<Field label="Zonas atendidas (una por línea)" full><textarea value={areasText} onChange={e=>setAreasText(e.target.value)}/></Field></div>}
    {step===4&&<div className={styles.checks}>{(Object.keys(verificationLabels) as AssistedVerification["type"][]).map(type=>{const current=verifications.find(item=>item.type===type);return <div className={styles.check} key={type}><input type="checkbox" checked={Boolean(current)} onChange={()=>toggleVerification(type)}/><div><strong>{verificationLabels[type]}</strong>{current&&<input aria-label={`Nota de ${verificationLabels[type]}`} value={current.note} onChange={e=>setVerifications(value=>value.map(item=>item.type===type?{...item,note:e.target.value}:item))}/>}</div></div>})}</div>}
    {step===5&&<div className={styles.form}><div className={styles.notice}><strong>Antes de publicar</strong><br/>El perfil quedará visible inmediatamente. Su propietario podrá reclamarlo con un enlace de un solo uso y los últimos cuatro dígitos del teléfono.</div><label className={styles.check}><input type="checkbox" checked={consentConfirmed} onChange={e=>setConsentConfirmed(e.target.checked)}/><span><strong>La persona autorizó a Tequit a crear y publicar esta ficha</strong><br/><small>Consentimiento recibido por {source==="in_person"?"visita en persona":source==="call"?"llamada":"WhatsApp"}.</small></span></label><Field label="Nota de consentimiento"><textarea value={consentNote} onChange={e=>setConsentNote(e.target.value)} placeholder="Ej. Confirmó durante visita del 31 de agosto."/></Field>{matches.length>0&&<><label className={styles.check}><input type="checkbox" checked={duplicateReviewed} onChange={e=>setDuplicateReviewed(e.target.checked)}/><span><strong>Revisé los posibles duplicados</strong></span></label><Field label="Resultado de la revisión"><textarea value={duplicateNote} onChange={e=>setDuplicateNote(e.target.value)}/></Field></>}</div>}
    <div className={styles.actions}><div>{step>0&&<button className={dashboardStyles.secondary} type="button" onClick={()=>setStep(value=>value-1)} disabled={busy}>Atrás</button>}<button className={dashboardStyles.ghost} type="button" onClick={()=>save(true)} disabled={busy}>Guardar</button></div>{step<5?<button className={dashboardStyles.primary} type="button" onClick={next} disabled={busy}>Guardar y continuar</button>:<button className={dashboardStyles.primary} type="button" onClick={publish} disabled={busy}>Confirmar y publicar</button>}</div></section><aside className={styles.aside}><h2>{name||`Nuevo ${title}`}</h2><p>{profession||"Actividad pendiente"}<br/>{zone}</p><ol>{steps.map((label,index)=><li key={label}><strong>{index===step?"Ahora: ":index<step?"Listo: ":""}</strong>{label}</li>)}</ol>{id&&<><small>Borrador {id.slice(0,8)}</small><Link href="/admin/altas">Salir a la cola</Link></>}</aside></div></div>;
}

function Field({label,full,children}:{label:string;full?:boolean;children:React.ReactNode}){return <label className={`${styles.field} ${full?styles.full:""}`}><span>{label}</span>{children}</label>}
function Upload({label,multiple,onFiles}:{label:string;multiple?:boolean;onFiles:(files:FileList|null)=>void}){return <label className={styles.upload}><ImagePlus size={30}/><strong>{label}</strong><span>Toca para tomar o elegir {multiple?"fotos":"una imagen"}</span><input hidden type="file" accept="image/jpeg,image/png,image/webp" capture="environment" multiple={multiple} onChange={e=>onFiles(e.target.files)}/></label>}
