"use client";

import Image from "next/image";
import {useEffect,useMemo,useRef,useState} from "react";
import {Camera,Crop,Images,LoaderCircle,Trash2,UploadCloud} from "lucide-react";
import {dashboardStyles} from "@/components/dashboard-components";
import styles from "@/components/assisted-onboarding.module.css";

type Role="avatar"|"cover"|"portfolio";
type CropState={zoom:number;x:number;y:number};
type Pending={id:string;file:File;url:string;crop:CropState};
export type AssistedMedia={avatar?:string;cover?:string;portfolio:string[]};

const accept="image/jpeg,image/png,image/webp";
const emptyCrop={zoom:1,x:0,y:0};

function makePending(files:File[]){return files.map(file=>({id:crypto.randomUUID(),file,url:URL.createObjectURL(file),crop:{...emptyCrop}}))}
async function cropFile(item:Pending,role:"avatar"|"cover"){const bitmap=await createImageBitmap(item.file,{imageOrientation:"from-image"});const width=role==="avatar"?1200:1600;const height=role==="avatar"?1200:900;const base=Math.max(width/bitmap.width,height/bitmap.height);const scale=base*item.crop.zoom;const drawWidth=bitmap.width*scale;const drawHeight=bitmap.height*scale;const overflowX=Math.max(0,drawWidth-width);const overflowY=Math.max(0,drawHeight-height);const offsetX=item.crop.x/100*overflowX/2;const offsetY=item.crop.y/100*overflowY/2;const canvas=document.createElement("canvas");canvas.width=width;canvas.height=height;const context=canvas.getContext("2d");if(!context)throw new Error("No pudimos preparar la imagen.");context.drawImage(bitmap,(width-drawWidth)/2+offsetX,(height-drawHeight)/2+offsetY,drawWidth,drawHeight);bitmap.close();const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,"image/webp",.88));if(!blob)throw new Error("No pudimos recortar la imagen.");return new File([blob],`${role}-${Date.now()}.webp`,{type:"image/webp"})}

export function AssistedMediaEditor({kind,initial,onUpload,busy}:{kind:"provider"|"business";initial?:AssistedMedia;onUpload:(files:File[],role:Role)=>Promise<string[]>;busy:boolean}){const[pending,setPending]=useState<Record<Role,Pending[]>>({avatar:[],cover:[],portfolio:[]});const[uploaded,setUploaded]=useState<AssistedMedia>(initial??{portfolio:[]});const[active,setActive]=useState<Role|null>(null);const[validation,setValidation]=useState("");const refs=useRef<Pending[]>([]);useEffect(()=>{refs.current=Object.values(pending).flat()},[pending]);useEffect(()=>()=>refs.current.forEach(item=>URL.revokeObjectURL(item.url)),[]);const totalPortfolio=uploaded.portfolio.length+pending.portfolio.length;
  function select(role:Role,list:FileList|null){if(!list?.length)return;setValidation("");const incoming=Array.from(list);const valid=incoming.filter(file=>file.size<=8*1024*1024&&accept.includes(file.type));if(valid.length!==incoming.length)setValidation("Algunas imágenes no se agregaron. Usa JPG, PNG o WebP de máximo 8 MB.");const room=role==="portfolio"?Math.max(0,10-totalPortfolio):1;if(role==="portfolio"&&valid.length>room)setValidation(`Sólo puedes agregar ${room} trabajo${room===1?"":"s"} más.`);const additions=makePending((role==="portfolio"?valid.slice(0,room):valid.slice(0,1)));setPending(value=>{value[role].forEach(item=>role!=="portfolio"&&URL.revokeObjectURL(item.url));return{...value,[role]:role==="portfolio"?[...value.portfolio,...additions]:additions}})}
  function remove(role:Role,id:string){setPending(value=>{const item=value[role].find(entry=>entry.id===id);if(item)URL.revokeObjectURL(item.url);return{...value,[role]:value[role].filter(entry=>entry.id!==id)}})}
  function updateCrop(role:"avatar"|"cover",field:keyof CropState,value:number){setPending(current=>({...current,[role]:current[role].map((item,index)=>index===0?{...item,crop:{...item.crop,[field]:value}}:item)}))}
  async function upload(role:Role){if(!pending[role].length)return;setActive(role);try{const files=role==="portfolio"?pending.portfolio.map(item=>item.file):[await cropFile(pending[role][0],role)];const urls=await onUpload(files,role);setUploaded(value=>role==="portfolio"?{...value,portfolio:[...value.portfolio,...urls]}:{...value,[role]:urls[0]??value[role]});pending[role].forEach(item=>URL.revokeObjectURL(item.url));setPending(value=>({...value,[role]:[]}))}finally{setActive(null)}}
  return <div className={styles.mediaEditor}>{validation&&<p className={styles.error} role="alert">{validation}</p>}
    <MediaSection title={kind==="provider"?"Foto de perfil":"Logo del negocio"} description="Formato cuadrado. Ajusta el encuadre antes de subir." role="avatar" pending={pending.avatar} uploaded={uploaded.avatar} busy={busy||active!==null} active={active} onSelect={select} onRemove={remove} onCrop={updateCrop} onUpload={upload}/>
    <MediaSection title="Portada" description="Formato horizontal para la cabecera del sitio." role="cover" pending={pending.cover} uploaded={uploaded.cover} busy={busy||active!==null} active={active} onSelect={select} onRemove={remove} onCrop={updateCrop} onUpload={upload}/>
    <MediaSection title="Trabajos realizados" description={`${totalPortfolio} de 10. Se conserva el encuadre original.`} role="portfolio" pending={pending.portfolio} uploaded={uploaded.portfolio} busy={busy||active!==null} active={active} onSelect={select} onRemove={remove} onUpload={upload}/>
  </div>}

type SectionProps={title:string;description:string;role:Role;pending:Pending[];uploaded?:string|string[];busy:boolean;active:Role|null;onSelect:(role:Role,files:FileList|null)=>void;onRemove:(role:Role,id:string)=>void;onCrop?:(role:"avatar"|"cover",field:keyof CropState,value:number)=>void;onUpload:(role:Role)=>void};
function MediaSection({title,description,role,pending,uploaded,busy,active,onSelect,onRemove,onCrop,onUpload}:SectionProps){const camera=useRef<HTMLInputElement>(null);const gallery=useRef<HTMLInputElement>(null);const uploadedList=useMemo(()=>Array.isArray(uploaded)?uploaded:uploaded?[uploaded]:[],[uploaded]);const editable=role!=="portfolio"?pending[0]:undefined;return <section className={styles.mediaSection}><header><div><h3>{title}</h3><p>{description}</p></div><div className={styles.mediaSources}><button type="button" className={dashboardStyles.secondary} onClick={()=>camera.current?.click()} disabled={busy}><Camera size={17}/>Tomar foto</button><button type="button" className={dashboardStyles.secondary} onClick={()=>gallery.current?.click()} disabled={busy}><Images size={17}/>Galería</button></div><input ref={camera} hidden type="file" accept={accept} capture="environment" multiple={role==="portfolio"} onChange={event=>{onSelect(role,event.target.files);event.target.value=""}}/><input ref={gallery} hidden type="file" accept={accept} multiple={role==="portfolio"} onChange={event=>{onSelect(role,event.target.files);event.target.value=""}}/></header>
    {!pending.length&&!uploadedList.length&&<div className={styles.mediaEmpty}><Images size={28}/><span>Aún no hay imágenes</span></div>}
    {editable&&<div className={styles.cropEditor}><div className={`${styles.cropViewport} ${role==="avatar"?styles.cropSquare:styles.cropCover}`}><Image src={editable.url} alt={`Vista previa de ${title}`} fill unoptimized sizes="(max-width: 850px) 100vw, 720px" style={{objectFit:"cover",transform:`scale(${editable.crop.zoom}) translate(${editable.crop.x/2}%,${editable.crop.y/2}%)`}}/></div><div className={styles.cropControls}><span><Crop size={16}/>Ajustar recorte</span><label>Zoom<input type="range" min="1" max="2.5" step="0.05" value={editable.crop.zoom} onChange={event=>onCrop?.(role as "avatar"|"cover","zoom",Number(event.target.value))}/></label><label>Horizontal<input type="range" min="-100" max="100" value={editable.crop.x} onChange={event=>onCrop?.(role as "avatar"|"cover","x",Number(event.target.value))}/></label><label>Vertical<input type="range" min="-100" max="100" value={editable.crop.y} onChange={event=>onCrop?.(role as "avatar"|"cover","y",Number(event.target.value))}/></label><button type="button" className={dashboardStyles.ghost} onClick={()=>onRemove(role,editable.id)}><Trash2 size={16}/>Quitar</button></div></div>}
    {role==="portfolio"&&pending.length>0&&<div className={styles.mediaGrid}>{pending.map(item=><figure className={styles.mediaPreview} key={item.id}><Image src={item.url} alt="Trabajo pendiente de subir" fill unoptimized sizes="160px"/><figcaption>Pendiente</figcaption><button type="button" onClick={()=>onRemove(role,item.id)} aria-label="Quitar imagen"><Trash2 size={17}/></button></figure>)}</div>}
    {uploadedList.length>0&&<div><p className={styles.mediaLabel}>Ya guardadas</p><div className={styles.mediaGrid}>{uploadedList.map((url,index)=><figure className={styles.mediaPreview} key={`${url}-${index}`}><Image src={url} alt={`${title} guardada ${index+1}`} fill unoptimized sizes="160px"/><figcaption>Guardada</figcaption></figure>)}</div></div>}
    {pending.length>0&&<button type="button" className={dashboardStyles.primary} onClick={()=>onUpload(role)} disabled={busy}>{active===role?<LoaderCircle className="spin" size={18}/>:<UploadCloud size={18}/>}Subir {pending.length>1?`${pending.length} imágenes`:"imagen"}</button>}
  </section>}
