import Link from "next/link";
import { BadgeCheck, Building2, MapPin, Star } from "lucide-react";
import type { Business, Provider } from "@/types";
import { SaveButton } from "@/components/save-button";

export function Rating({ value,count }: { value:number; count:number }) { return <span className="rating" aria-label={`${value} de 5, ${count} reseñas`}><Star size={16} aria-hidden/><strong>{value.toFixed(1)}</strong><span>({count})</span></span> }
const initials=(name:string)=>name.split(" ").slice(0,2).map(v=>v[0]).join("");
export function ProviderCard({provider,variant="grid"}: {provider:Provider;variant?:"grid"|"list"|"compact"}) { return <article className={`entity-card provider-card entity-card-${variant}`}><div className="entity-card-head"><div className="avatar" aria-hidden>{initials(provider.name)}</div><div className="entity-card-identity"><p className="entity-kicker">{provider.profession}</p><h3><Link href={`/p/${provider.slug}`}>{provider.name}</Link></h3><Rating value={provider.rating} count={provider.reviewCount}/></div><SaveButton slug={provider.slug} type="provider"/></div><div className="tag-list" aria-label="Servicios destacados">{provider.services.slice(0,3).map(s=><span key={s.id}>{s.name}</span>)}</div><div className="entity-trust"><BadgeCheck size={17} aria-hidden/>{provider.verifications.length} verificaciones</div><div className="entity-card-foot"><span><MapPin size={16} aria-hidden/> {provider.zone}</span><Link className="text-link" href={`/p/${provider.slug}`}>Ver perfil <span aria-hidden>→</span></Link></div></article> }
export function BusinessCard({business,variant="grid"}: {business:Business;variant?:"grid"|"list"|"compact"}) { return <article className={`entity-card business-card entity-card-${variant}`}><div className="business-card-visual"><Building2 size={28} aria-hidden/><span>Negocio local</span></div><div className="business-card-save"><SaveButton slug={business.slug} type="business"/></div><p className="entity-kicker">{business.category}</p><h3><Link href={`/n/${business.slug}`}>{business.name}</Link></h3><Rating value={business.rating} count={business.reviewCount}/><p className="entity-summary">{business.description}</p><div className="tag-list">{business.services.slice(0,3).map(s=><span key={s.id}>{s.name}</span>)}</div><div className="entity-card-foot"><span><MapPin size={16} aria-hidden/> {business.zone}</span><Link className="text-link" href={`/n/${business.slug}`}>Ver negocio <span aria-hidden>→</span></Link></div></article> }
