import Link from "next/link";
import { BadgeCheck, MapPin, Star } from "lucide-react";
import type { Business, Provider } from "@/types";
import { SaveButton } from "@/components/save-button";

export function Rating({ value,count }: { value:number; count:number }) { return <span className="rating" aria-label={`${value} de 5, ${count} reseñas`}><Star size={15}/>{value.toFixed(1)} <span className="muted">· {count} reseñas</span></span> }
const initials=(name:string)=>name.split(" ").slice(0,2).map(v=>v[0]).join("");
export function ProviderCard({provider}: {provider:Provider}) { return <article className="provider-card"><div className="card-top"><div className="avatar" aria-hidden>{initials(provider.name)}</div><div><p className="eyebrow">{provider.profession}</p><h3 className="card-title"><Link href={`/p/${provider.slug}`}>{provider.name}</Link></h3><div className="card-meta"><Rating value={provider.rating} count={provider.reviewCount}/></div></div><div style={{marginLeft:"auto"}}><SaveButton slug={provider.slug} type="provider"/></div></div><div className="card-services">{provider.services.slice(0,3).map(s=><span key={s.id}>{s.name}</span>)}</div><div className="verified"><BadgeCheck size={16} style={{display:"inline",marginRight:5}}/>{provider.verifications.length} verificaciones</div><div className="card-foot"><span className="muted"><MapPin size={15} style={{display:"inline"}}/> {provider.zone}</span><Link className="btn btn-ghost" href={`/p/${provider.slug}`}>Ver perfil →</Link></div></article> }
export function BusinessCard({business}: {business:Business}) { const events=business.category==="Eventos"; return <article className="business-card"><div className={`business-visual ${events?"events":""}`}><div><p className="eyebrow" style={{color:"white"}}>Negocio local</p><h3 style={{fontSize:"1.5rem",margin:0}}>{business.name}</h3></div></div><div style={{position:"absolute",right:30,top:132}}><SaveButton slug={business.slug} type="business"/></div><Rating value={business.rating} count={business.reviewCount}/><p className="muted" style={{margin:"12px 0"}}>{business.description}</p><div className="card-services">{business.services.slice(0,3).map(s=><span key={s.id}>{s.name}</span>)}</div><div className="card-foot"><span className="muted"><MapPin size={15} style={{display:"inline"}}/> {business.zone}</span><Link className="btn btn-ghost" href={`/n/${business.slug}`}>Ver negocio →</Link></div></article> }
