"use client";
import {FormEvent,useState} from "react";
import {useRouter} from "next/navigation";
import {Loader2,ShieldCheck} from "lucide-react";
import {LegalConsentFields}from "@/components/legal-consent-fields";
import styles from "@/components/identity-redesign.module.css";

export function ClaimProfileForm({token}:{token:string}){
  const router=useRouter();const[mode,setMode]=useState<"create"|"signin">("create");const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[legalError,setLegalError]=useState("");
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget));const acceptTerms=values.acceptTerms==="true",acceptPrivacy=values.acceptPrivacy==="true";if(mode==="create"&&(!acceptTerms||!acceptPrivacy)){setLegalError("Debes aceptar ambos documentos para crear tu cuenta.");return}setLegalError("");setBusy(true);setError("");const response=await fetch("/api/claims",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...values,acceptTerms,acceptPrivacy,mode,token})});const data=await response.json();if(response.status===428&&data.code==="PHONE_MIGRATION_REQUIRED"){router.push(`/cuenta/activar-celular?next=${encodeURIComponent(`/reclamar/${token}`)}`);return}if(!response.ok){setError(data.error??"No pudimos reclamar el perfil.");setBusy(false);return}router.push(data.destination);router.refresh()}
  return <div><div className={styles.accountTypeGrid}><button type="button" className={mode==="create"?styles.accountTypeActive:styles.accountType} onClick={()=>{setMode("create");setLegalError("")}}>Crear mi cuenta</button><button type="button" className={mode==="signin"?styles.accountTypeActive:styles.accountType} onClick={()=>{setMode("signin");setLegalError("")}}>Ya tengo cuenta</button></div><form className={styles.formGrid} onSubmit={submit}>{mode==="create"&&<div className={`${styles.fieldGroup} ${styles.fieldGroupFull}`}><label htmlFor="claim-name">Tu nombre</label><input className={styles.field} id="claim-name" name="name" autoComplete="name" required/></div>}<div className={`${styles.fieldGroup} ${styles.fieldGroupFull}`}><label htmlFor="claim-phone">Número asociado al perfil</label><input className={styles.field} id="claim-phone" name="phone" inputMode="tel" autoComplete="tel" placeholder="311 000 0000" required/></div>{mode==="create"&&<div className={`${styles.fieldGroup} ${styles.fieldGroupFull}`}><label htmlFor="claim-email">Correo de recuperación <span aria-hidden>(opcional)</span></label><input className={styles.field} id="claim-email" name="recoveryEmail" type="email" autoComplete="email"/></div>}<div className={`${styles.fieldGroup} ${styles.fieldGroupFull}`}><label htmlFor="claim-password">Contraseña</label><input className={styles.field} id="claim-password" name="password" type="password" minLength={8} autoComplete={mode==="create"?"new-password":"current-password"} required/></div><p className={`${styles.fieldHelp} ${styles.fieldGroupFull}`}>El número debe coincidir con el WhatsApp registrado por Tequit. Durante la beta quedará pendiente de OTP.</p>{mode==="create"&&<LegalConsentFields error={legalError}/>} {error&&<p className={styles.formError} role="alert">{error}</p>}<button className={`btn btn-primary ${styles.fieldGroupFull}`} disabled={busy}>{busy?<Loader2 className="animate-spin"/>:<ShieldCheck size={18}/>}Reclamar y administrar</button></form></div>;
}
