"use client";
import {FormEvent,useState}from"react";import Image from"next/image";import{ArrowLeft,ArrowRight,Check,Loader2}from"lucide-react";import{useRouter}from"next/navigation";import{AssistedMediaEditor,type MediaRole}from"@/components/assisted-media-editor";import{createClient}from"@/lib/supabase/client";import styles from"@/components/provider-onboarding.module.css";
export type ProviderOnboardingInitial={name:string;profession:string;phone:string;zone:string;bio:string;service:string;serviceDescription:string;avatarPath:string|null;avatarUrl?:string;coverPath:string|null;coverUrl?:string;step:number};
export function ProviderOnboardingForm({name,phone,kind="provider",initial}:{name:string;phone:string;kind?:"provider"|"business";initial?:ProviderOnboardingInitial}){const router=useRouter();const[step,setStep]=useState(Math.min(initial?.step??1,4));const[busy,setBusy]=useState(false);const[error,setError]=useState("");const[data,setData]=useState<ProviderOnboardingInitial>(initial??{name,profession:"",phone,zone:"Tepic, Nayarit",bio:"",service:"",serviceDescription:"",avatarPath:null,coverPath:null,step:1});const isBusiness=kind==="business";function field(key:keyof ProviderOnboardingInitial,value:string){setData(current=>({...current,[key]:value}));setError("")}
async function save(nextStep:number,action:"save"|"publish"="save"){setBusy(true);setError("");const response=await fetch("/api/account/provider",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...data,kind,action,step:nextStep,firstService:data.service})});const body=await response.json();setBusy(false);if(!response.ok){setError(body.error??"No pudimos guardar tu perfil.");return false}if(body.destination){router.push(body.destination);router.refresh();return true}setData(current=>({...current,step:nextStep}));setStep(nextStep);return true}
async function upload(files:File[],role:MediaRole){const supabase=createClient();const{data:{user}}=await supabase.auth.getUser();if(!user)throw new Error("Tu sesión terminó.");const bucket=role==="avatar"?"avatars":"provider-work";const urls:string[]=[];for(const file of files){const path=`${user.id}/${crypto.randomUUID()}.webp`;const{error:uploadError}=await supabase.storage.from(bucket).upload(path,file,{contentType:"image/webp",upsert:false});if(uploadError)throw uploadError;const{data:url}=supabase.storage.from(bucket).getPublicUrl(path);urls.push(url.publicUrl);setData(current=>({...current,[role==="avatar"?"avatarPath":"coverPath"]:path,[role==="avatar"?"avatarUrl":"coverUrl"]:url.publicUrl}))}return urls}
function next(){if(step===1&&(!data.name.trim()||!data.profession.trim()||data.phone.replace(/\D/g,"").length<10||!data.zone.trim()))return setError("Completa tu nombre público, actividad, WhatsApp y zona.");if(step===2&&(data.bio.trim().length<20||!data.service.trim()||data.serviceDescription.trim().length<10))return setError("Agrega una presentación y describe al menos un servicio.");if(step===3&&(!data.avatarPath||!data.coverPath))return setError("Sube tu foto de perfil y una portada para continuar.");void save(Math.min(4,step+1))}
if(isBusiness)return <LegacyBusinessForm data={data} busy={busy} error={error} onField={field} onBusy={setBusy} onError={setError}/>;return <section className={styles.wizard} aria-label="Completar perfil de prestador"><header><p>Paso {step} de 4</p><div className={styles.progress} aria-label={`${step} de 4 pasos`}>{[1,2,3,4].map(item=><span className={item<=step?styles.done:""} key={item}/>)}</div><h2>{step===1?"Datos de tu perfil":step===2?"Presentación y servicio":step===3?"Fotos de tu perfil":"Revisa y publica"}</h2></header>
{step===1&&<div className={styles.formGrid}><Field label="Nombre público"><input value={data.name} onChange={e=>field("name",e.target.value)} required/></Field><Field label="Oficio o actividad"><input value={data.profession} onChange={e=>field("profession",e.target.value)} placeholder="Ej. Electricista" required/></Field><Field label="WhatsApp público"><input value={data.phone} onChange={e=>field("phone",e.target.value)} inputMode="tel" required/></Field><Field label="Zona de atención"><input value={data.zone} onChange={e=>field("zone",e.target.value)} required/></Field></div>}
{step===2&&<div className={styles.formGrid}><Field label="Sobre tu trabajo" wide><textarea value={data.bio} onChange={e=>field("bio",e.target.value)} minLength={20} maxLength={1200} placeholder="Cuenta qué haces, cómo trabajas y qué puede esperar un cliente."/></Field><Field label="Primer servicio"><input value={data.service} onChange={e=>field("service",e.target.value)} placeholder="Ej. Instalaciones eléctricas"/></Field><Field label="Descripción del servicio"><textarea value={data.serviceDescription} onChange={e=>field("serviceDescription",e.target.value)} minLength={10} maxLength={500}/></Field></div>}
{step===3&&<AssistedMediaEditor kind="provider" roles={["avatar","cover"]} initial={{avatar:data.avatarUrl,cover:data.coverUrl,portfolio:[]}} onUpload={upload} busy={busy}/>}
{step===4&&<div className={styles.summary}><div>{data.avatarUrl?<Image src={data.avatarUrl} alt="Vista previa de tu perfil" width={64} height={64}/>:<span/>}<div><strong>{data.name}</strong><p>{data.profession} · {data.zone}</p></div></div><p>{data.bio}</p><dl><div><dt>Servicio</dt><dd>{data.service}</dd></div><div><dt>WhatsApp</dt><dd>{data.phone}</dd></div><div><dt>Portada</dt><dd>{data.coverPath?"Lista":"Pendiente"}</dd></div></dl></div>}
{error&&<p className={styles.error} role="alert">{error}</p>}<footer>{step>1?<button type="button" className="btn btn-secondary" onClick={()=>setStep(value=>value-1)} disabled={busy}><ArrowLeft/>Atrás</button>:<span/>}{step<4?<button type="button" className="btn btn-primary" onClick={next} disabled={busy}>{busy?<Loader2 className="animate-spin"/>:<ArrowRight/>}{busy?"Guardando…":"Guardar y continuar"}</button>:<button type="button" className="btn btn-primary" onClick={()=>save(4,"publish")} disabled={busy}>{busy?<Loader2 className="animate-spin"/>:<Check/>}{busy?"Publicando…":"Publicar mi perfil"}</button>}</footer></section>}
function Field({label,wide,children}:{label:string;wide?:boolean;children:React.ReactNode}){return <label className={wide?styles.wide:""}><span>{label}</span>{children}</label>}
function LegacyBusinessForm({data,busy,error,onField,onBusy,onError}:{data:ProviderOnboardingInitial;busy:boolean;error:string;onField:(key:keyof ProviderOnboardingInitial,value:string)=>void;onBusy:(v:boolean)=>void;onError:(v:string)=>void}){const router=useRouter();async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();onBusy(true);onError("");const response=await fetch("/api/account/provider",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...data,kind:"business",firstService:data.service})});const body=await response.json();onBusy(false);if(!response.ok)return onError(body.error??"No pudimos crear el negocio.");router.push(body.destination);router.refresh()}return <form className="account-provider-form" onSubmit={submit}><Field label="Nombre del negocio"><input value={data.name} onChange={e=>onField("name",e.target.value)} required/></Field><Field label="Categoría principal"><input value={data.profession} onChange={e=>onField("profession",e.target.value)} required/></Field><Field label="WhatsApp público"><input value={data.phone} onChange={e=>onField("phone",e.target.value)} required/></Field><Field label="Zona"><input value={data.zone} onChange={e=>onField("zone",e.target.value)} required/></Field><Field label="Sobre el negocio"><textarea value={data.bio} onChange={e=>onField("bio",e.target.value)} minLength={20} required/></Field><Field label="Primer servicio"><input value={data.service} onChange={e=>onField("service",e.target.value)} required/></Field>{error&&<p role="alert">{error}</p>}<button className="btn btn-primary" disabled={busy}>{busy?"Creando…":"Terminar perfil de negocio"}</button></form>}
