import Link from "next/link";
import { BadgeCheck, ChevronRight, Filter, MapPin, SearchX, ShieldCheck } from "lucide-react";
import { BusinessCard, ProviderCard } from "@/components/cards";
import type { SearchResult } from "@/types";
import styles from "@/components/public-redesign.module.css";

export function TrustProof() { return <div className={styles.trustProof} aria-label="Cómo te ayuda Tequit"><span><BadgeCheck size={19} aria-hidden/><strong>Señales de confianza</strong><small>Revisa identidad y referencias disponibles.</small></span><span><ShieldCheck size={19} aria-hidden/><strong>Contacto directo</strong><small>Tú acuerdas alcance y pago por WhatsApp.</small></span><span><MapPin size={19} aria-hidden/><strong>Hecho en Tepic</strong><small>Opciones locales y zonas claramente indicadas.</small></span></div> }
export function Breadcrumbs({ current }: { current: string }) { return <nav className={styles.breadcrumbs} aria-label="Ruta de navegación"><Link href="/">Inicio</Link><ChevronRight size={15} aria-hidden/><Link href="/buscar">Servicios</Link><ChevronRight size={15} aria-hidden/><span aria-current="page">{current}</span></nav> }

export function FilterBar({ query, type, verified }: { query: string; type: "all"|"provider"|"business"; verified: boolean }) { const href=(nextType:string,nextVerified=verified)=>`/buscar?q=${encodeURIComponent(query)}${nextType!=="all"?`&type=${nextType}`:""}${nextVerified?"&verified=true":""}`; return <div className={styles.filterBar} aria-label="Filtrar resultados"><Link className={`chip ${type==="all"?"active":""}`} href={href("all")}>Todos</Link><Link className={`chip ${type==="provider"?"active":""}`} href={href("provider")}>Personas</Link><Link className={`chip ${type==="business"?"active":""}`} href={href("business")}>Negocios</Link><Link className={`chip ${verified?"active":""}`} href={href(type,!verified)} aria-pressed={verified}>Verificados</Link></div> }
export function FilterSidebar(props: Parameters<typeof FilterBar>[0]) { return <aside className={styles.filterSidebar} aria-label="Filtros disponibles"><p className="eyebrow"><Filter size={14} aria-hidden/> Afinar búsqueda</p><h2>Tipo de opción</h2><FilterBar {...props}/><p>Mostramos sólo filtros que ya modifican los resultados. La zona se indica en cada ficha.</p></aside> }
export function MobileFilters(props: Parameters<typeof FilterBar>[0]) { return <details className={styles.mobileFilters}><summary><Filter size={18} aria-hidden/> Filtrar resultados</summary><FilterBar {...props}/></details> }
export function SearchResults({results}:{results:SearchResult[]}) { return <div className={styles.resultList}>{results.map(result=>result.provider?<ProviderCard key={`provider-${result.provider.id}`} provider={result.provider} variant="list"/>:result.business?<BusinessCard key={`business-${result.business.id}`} business={result.business} variant="list"/>:null)}</div> }
export function DiscoveryEmpty({query}:{query?:string}) { return <div className={styles.emptyState}><SearchX size={30} aria-hidden/><p className="eyebrow">Sin coincidencia exacta</p><h2>Cuéntanos qué necesitas</h2><p>{query?`No encontramos “${query}” entre las opciones actuales.`:"Aún no hay opciones que coincidan con estos filtros."} Puedes publicar la necesidad sin crear una cuenta.</p><Link className="btn btn-primary" href={`/solicitar${query?`?service=${encodeURIComponent(query)}`:""}`}>Publicar necesidad</Link></div> }
