"use client";
import {FormEvent,useState} from "react";
import {useRouter} from "next/navigation";
import {KeyRound,Loader2,Mail} from "lucide-react";
import styles from "@/components/identity-redesign.module.css";

export function RequestRecoveryForm(){const[busy,setBusy]=useState(false);const[done,setDone]=useState(false);const[error,setError]=useState("");async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const email=String(new FormData(event.currentTarget).get("email"));const response=await fetch("/api/auth/recovery",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email})});const data=await response.json();setBusy(false);if(!response.ok){setError(data.error);return}setDone(true)}if(done)return <div className={styles.successState}><Mail size={34}/><h2>Revisa tu correo</h2><p>Si está confirmado y asociado a una cuenta, recibirás un enlace para cambiar la contraseña.</p></div>;return <form className={styles.formGrid} onSubmit={submit}><div className={`${styles.fieldGroup} ${styles.fieldGroupFull}`}><label htmlFor="recovery-email">Correo de recuperación confirmado</label><input className={styles.field} id="recovery-email" name="email" type="email" autoComplete="email" required/></div>{error&&<p className={styles.formError}>{error}</p>}<button className={`btn btn-primary ${styles.fieldGroupFull}`} disabled={busy}>{busy?<Loader2 className="animate-spin"/>:<Mail size={18}/>}Enviar enlace</button></form>}
export function ResetPasswordForm(){const router=useRouter();const[busy,setBusy]=useState(false);const[error,setError]=useState("");async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);const password=String(new FormData(event.currentTarget).get("password"));const response=await fetch("/api/auth/change-password",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({password})});const data=await response.json();if(!response.ok){setError(data.error);setBusy(false);return}router.push("/cuenta");router.refresh()}return <form className={styles.formGrid} onSubmit={submit}><div className={`${styles.fieldGroup} ${styles.fieldGroupFull}`}><label htmlFor="reset-password">Nueva contraseña</label><input className={styles.field} id="reset-password" name="password" type="password" minLength={8} autoComplete="new-password" required/></div>{error&&<p className={styles.formError}>{error}</p>}<button className={`btn btn-primary ${styles.fieldGroupFull}`} disabled={busy}>{busy?<Loader2 className="animate-spin"/>:<KeyRound size={18}/>}Guardar contraseña</button></form>}
export function RecoveryEmailForm({current}:{current?:string|null}){const[busy,setBusy]=useState(false);const[message,setMessage]=useState("");async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);const email=String(new FormData(event.currentTarget).get("email"));const response=await fetch("/api/account/recovery-email",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email})});const data=await response.json();setMessage(response.ok?"Te enviamos un enlace para confirmar el correo.":data.error);setBusy(false)}return <form onSubmit={submit}><label htmlFor="account-recovery-email">Correo de recuperación</label><input className="field" id="account-recovery-email" name="email" type="email" defaultValue={current??""} required/><button className="btn btn-secondary" disabled={busy}>{busy?"Enviando…":"Guardar y confirmar"}</button>{message&&<p role="status">{message}</p>}</form>}
