import {NextResponse} from "next/server";
import {z} from "zod";
import {allowRequest} from "@/lib/rate-limit";
import {normalizeMexicanPhone} from "@/lib/phone";
import {createAdminClient} from "@/lib/supabase/admin";
import {createClient} from "@/lib/supabase/server";

const schema=z.object({phone:z.string().trim().max(24),currentPassword:z.string().min(8).max(128)});
export async function POST(request:Request){if(!await allowRequest(request,"activate_phone",5,900))return NextResponse.json({error:"Demasiados intentos. Espera unos minutos."},{status:429});const parsed=schema.safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:"Revisa el celular y tu contraseña."},{status:400});const phone=normalizeMexicanPhone(parsed.data.phone);if(!phone)return NextResponse.json({error:"Escribe un celular mexicano de 10 dígitos."},{status:400});const supabase=await createClient();const{data:{user}}=await supabase.auth.getUser();if(!user?.email)return NextResponse.json({error:"Esta cuenta no necesita migración."},{status:409});const{error:passwordError}=await supabase.auth.signInWithPassword({email:user.email,password:parsed.data.currentPassword});if(passwordError)return NextResponse.json({error:"La contraseña actual no coincide."},{status:401});const admin=createAdminClient();if(!admin)return NextResponse.json({error:"Servicio temporalmente no disponible."},{status:503});const{data:duplicate}=await admin.from("profiles").select("id").eq("phone_e164",phone).neq("id",user.id).maybeSingle();if(duplicate)return NextResponse.json({error:"Ese celular ya está asociado a otra cuenta. Contacta a soporte para revisarlo."},{status:409});const{error}=await admin.auth.admin.updateUserById(user.id,{phone,phone_confirm:true});if(error)return NextResponse.json({error:"No pudimos activar ese celular. Revisa si ya está registrado."},{status:409});await admin.from("profiles").update({phone_e164:phone,phone:phone,phone_login_enabled_at:new Date().toISOString(),phone_verified_at:null,phone_verification_method:null}).eq("id",user.id);await admin.from("admin_audit_logs").insert({action:"phone_login_activated",entity_type:"profile",entity_id:user.id,metadata:{source:"legacy_migration"}});return NextResponse.json({ok:true,destination:"/cuenta"})}
