import Link from "next/link";
import { AccountManager } from "@/components/account-manager";
import { SiteContainer } from "@/components/layout-primitives";
import { requireSession } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import styles from "@/components/identity-redesign.module.css";

export const metadata={title:"Mi cuenta"};
export default async function AccountPage(){const session=await requireSession();const supabase=await createClient();const{data:leads}=await supabase.from("leads").select("id,requested_service_text,status,created_at").eq("customer_profile_id",session.user.id).order("created_at",{ascending:false}).limit(20);return <main className={styles.savedPage}><SiteContainer size="reading"><header className={styles.savedHeader}><p className="eyebrow">Cuenta personal</p><h1>Hola, {session.profile?.display_name??"bienvenido"}</h1><p>{session.profile?.must_change_password?"Antes de continuar, cambia la contraseña temporal de esta cuenta.":"Consulta tus solicitudes y administra tu acceso."}</p></header><section className={styles.detailSection}><h2>Mis solicitudes</h2>{leads?.length?<div>{leads.map((lead)=><article key={lead.id}><strong>{lead.requested_service_text}</strong><p className="muted">{lead.status} · {new Intl.DateTimeFormat("es-MX").format(new Date(lead.created_at))}</p></article>)}</div>:<p className="muted">Aún no has enviado solicitudes con esta cuenta.</p>}<Link className="btn btn-secondary" href="/solicitar">Publicar una necesidad</Link></section><section className={styles.detailSection}><h2>Guardados</h2><p>Los guardados se sincronizan al iniciar sesión en cada dispositivo.</p><Link className="btn btn-secondary" href="/guardados">Ver guardados</Link></section><section className={styles.detailSection}><h2>Seguridad</h2>{session.profile?.must_change_password&&<p role="alert"><strong>Cambio obligatorio:</strong> define una contraseña nueva para desbloquear el panel administrativo.</p>}<AccountManager/></section></SiteContainer></main>}
