import Link from "next/link";
import { AccountManager } from "@/components/account-manager";
import { ProviderOnboardingForm } from "@/components/provider-onboarding-form";
import { SiteContainer } from "@/components/layout-primitives";
import { requireSession } from "@/lib/auth";
import { createClient } from "@/lib/supabase/server";
import styles from "@/components/identity-redesign.module.css";

export const metadata={title:"Mi cuenta"};
export default async function AccountPage(){const session=await requireSession();const supabase=await createClient();const{data:leads}=await supabase.from("leads").select("id,requested_service_text,status,created_at").eq("customer_profile_id",session.user.id).order("created_at",{ascending:false}).limit(20);const isProvider=session.roles.includes("provider")||session.roles.includes("business_owner");return <main className={styles.savedPage}><SiteContainer size="reading"><header className={styles.savedHeader}><p className="eyebrow">Modo Usuario</p><h1>Hola, {session.profile?.display_name??"bienvenido"}</h1><p>{session.profile?.must_change_password?"Antes de continuar, cambia la contraseña temporal de esta cuenta.":"Tu información, actividad y modos de uso están aquí."}</p></header><section className={styles.detailSection}><h2>Tu cuenta</h2><p><strong>Correo:</strong> {session.user.email}</p><p><strong>Celular:</strong> {session.profile?.phone??"Pendiente"}</p></section><section className={styles.detailSection}><h2>Cambiar modo</h2>{isProvider?<><p>También tienes un perfil profesional. Entra al modo Prestador para administrar servicios, solicitudes y estadísticas.</p><Link className="btn btn-primary" href="/dashboard">Cambiar a modo Prestador</Link></>:<><p>Crea un perfil profesional dentro de esta misma cuenta. No perderás tus favoritos ni solicitudes.</p><details><summary className="btn btn-secondary">Quiero promocionarme</summary><ProviderOnboardingForm name={session.profile?.display_name??""} phone={session.profile?.phone??""}/></details></>}</section><section className={styles.detailSection}><h2>Mis solicitudes</h2>{leads?.length?<div>{leads.map((lead)=><article key={lead.id}><strong>{lead.requested_service_text}</strong><p className="muted">{lead.status} · {new Intl.DateTimeFormat("es-MX").format(new Date(lead.created_at))}</p></article>)}</div>:<p className="muted">Aún no has enviado solicitudes con esta cuenta.</p>}<Link className="btn btn-secondary" href="/solicitar">Publicar una necesidad</Link></section><section className={styles.detailSection}><h2>Favoritos</h2><p>Tus favoritos se sincronizan al iniciar sesión en cada dispositivo.</p><Link className="btn btn-secondary" href="/guardados">Ver favoritos</Link></section><section className={styles.detailSection}><h2>Seguridad</h2>{session.profile?.must_change_password&&<p role="alert"><strong>Cambio obligatorio:</strong> define una contraseña nueva para desbloquear el panel administrativo.</p>}<AccountManager/></section></SiteContainer></main>}
