export type LegalDocumentType="terms"|"privacy";
export type LegalSection={title:string;paragraphs?:string[];items?:string[]};
export type LegalDocument={type:LegalDocumentType;version:string;title:string;effectiveDate:string;summary:string;sections:LegalSection[]};

export const LEGAL_VERSION="2026-09-04";
export const LEGAL_OPERATOR="Tequit, proyecto en etapa beta operado desde Tepic, Nayarit";
export const LEGAL_CONTACT="privacidad@tequit.mx";

export const termsDocument:LegalDocument={
  type:"terms",version:LEGAL_VERSION,title:"Términos y Condiciones",effectiveDate:"4 de septiembre de 2026",
  summary:"Reglas provisionales para usar Tequit durante su etapa beta.",
  sections:[
    {title:"1. Identidad y alcance",paragraphs:[`${LEGAL_OPERATOR} (en adelante, “Tequit”) ofrece un directorio y herramientas de contacto entre personas que necesitan un trabajo, prestadores y negocios. La razón social y el domicilio formal del responsable están pendientes de definición y se incorporarán antes del lanzamiento comercial amplio.`,`Al crear una cuenta o utilizar las funciones de Tequit aceptas estos términos. Si no estás de acuerdo, no debes crear una cuenta ni usar funciones que requieran aceptación.`]},
    {title:"2. Elegibilidad, cuentas y seguridad",paragraphs:["Debes tener al menos 18 años y capacidad legal para contratar. La información registrada debe ser verdadera, actual y propia.","Eres responsable de resguardar tu contraseña, celular y sesiones. Informa de inmediato cualquier acceso no autorizado. Tequit puede solicitar comprobaciones para prevenir fraude o suplantación."]},
    {title:"3. Papel de Tequit",paragraphs:["Tequit facilita descubrimiento, publicación de perfiles y contacto. No es empleador, representante, contratista ni parte de los acuerdos celebrados entre usuarios, prestadores o negocios.","Cada parte decide precios, alcance, tiempos, garantías, forma de pago y condiciones del trabajo. Tequit no recibe pagos por esos acuerdos durante esta beta ni garantiza disponibilidad, calidad o resultados."]},
    {title:"4. Obligaciones de usuarios, prestadores y negocios",items:["Tratar a otras personas con respeto y cumplir la ley.","No publicar información falsa, servicios ilícitos, contenido discriminatorio, peligroso o engañoso.","Contar con permisos, experiencia y medidas de seguridad aplicables al trabajo ofrecido.","No usar Tequit para spam, fraude, extracción automatizada de datos o evasión de controles."]},
    {title:"5. Alta asistida y reclamación",paragraphs:["Tequit puede crear una ficha con autorización del prestador o negocio y la información que éste proporcione. Esa autorización permite publicar la ficha, pero no sustituye la aceptación de estos términos y de la política de privacidad.","El propietario podrá reclamar la ficha mediante un enlace privado y un celular coincidente. Tequit puede revocar enlaces, pedir evidencia adicional o rechazar transferencias cuando exista riesgo de suplantación."]},
    {title:"6. Contenido, fotografías y propiedad intelectual",paragraphs:["Conservas los derechos sobre el contenido que aportas. Otorgas a Tequit una licencia no exclusiva, mundial, gratuita y revocable al eliminar el contenido, para alojarlo, adaptarlo técnicamente, mostrarlo y promocionar tu ficha dentro y fuera del servicio.","Sólo debes subir material propio o que tengas autorización para usar. No publiques datos sensibles, imágenes de menores sin autorización ni fotografías que vulneren privacidad o derechos de terceros. Tequit puede retirar contenido denunciado o incompatible con estas reglas."]},
    {title:"7. WhatsApp, enlaces y terceros",paragraphs:["Al pulsar un enlace de WhatsApp u otro servicio externo sales de Tequit y aplican las condiciones de ese tercero. El número público del prestador puede mostrarse para facilitar contacto.","Tequit utiliza proveedores de infraestructura y mensajería. No controla interrupciones, políticas ni actos de esos terceros, aunque selecciona medidas razonables para operar la beta."]},
    {title:"8. Solicitudes y archivos",paragraphs:["Las solicitudes deben describir necesidades reales. Sus datos y adjuntos se destinan al solicitante, destinatario y personal autorizado de Tequit según corresponda.","No envíes documentos oficiales, datos financieros, contraseñas u otra información innecesaria. Los prestadores no deben reutilizar datos de solicitudes para fines distintos de atenderlas."]},
    {title:"9. Planes Free y Pro",paragraphs:["Free incluye las capacidades que la interfaz muestre como disponibles. Pro puede habilitar personalización o analítica adicional y, durante la beta, puede asignarse manualmente sin cobro.","Tequit puede ajustar límites y características futuras informándolo de forma clara. Una solicitud de Pro no crea por sí sola una suscripción ni una obligación de pago."]},
    {title:"10. Reseñas, verificación y moderación",paragraphs:["Las reseñas deben reflejar experiencias reales y pueden quedar pendientes de moderación. Tequit puede rechazar contenido ofensivo, fraudulento, irrelevante o manipulado.","Los distintivos de verificación indican únicamente la comprobación expresamente descrita; no son una certificación integral ni garantía del trabajo."]},
    {title:"11. Suspensión y terminación",paragraphs:["Tequit puede limitar, suspender o retirar cuentas y publicaciones por incumplimiento, riesgo de seguridad, denuncias razonables, requerimiento legal o protección de la comunidad. Cuando sea viable se permitirá aclarar la situación.","Puedes dejar de usar Tequit y solicitar eliminación de tu cuenta. Algunas evidencias legales, de seguridad o cumplimiento podrán conservarse durante el plazo necesario."]},
    {title:"12. Responsabilidad",paragraphs:["Tequit se ofrece en beta y puede presentar errores o interrupciones. En la medida permitida por la ley, Tequit no responde por acuerdos, daños, pérdidas, pagos, lesiones o controversias entre usuarios y prestadores.","Nada en estos términos limita derechos irrenunciables reconocidos por la legislación mexicana. Cada usuario debe evaluar al tercero y tomar precauciones adecuadas antes de contratar o ejecutar un trabajo."]},
    {title:"13. Cambios, legislación y contacto",paragraphs:["Podremos publicar nuevas versiones con fecha de vigencia. Cuando un cambio material requiera nueva aceptación, se solicitará antes de continuar con funciones afectadas.","Estos términos se interpretan provisionalmente conforme a las leyes de México y, cuando corresponda, ante autoridades competentes de Nayarit, sin afectar derechos de consumidores. Contacto: privacidad@tequit.mx."]}
  ]
};

export const privacyDocument:LegalDocument={
  type:"privacy",version:LEGAL_VERSION,title:"Aviso y Política de Privacidad",effectiveDate:"4 de septiembre de 2026",
  summary:"Cómo Tequit recopila, utiliza, comparte y protege datos durante su beta.",
  sections:[
    {title:"1. Responsable provisional",paragraphs:[`${LEGAL_OPERATOR} es el responsable provisional del tratamiento descrito aquí. La razón social y el domicilio formal están pendientes de definición y se incorporarán antes del lanzamiento comercial amplio. Contacto de privacidad: ${LEGAL_CONTACT}.`]},
    {title:"2. Datos que recopilamos",items:["Identidad y cuenta: nombre, celular, correo opcional, credenciales cifradas y rol.","Perfil público: profesión, zona, WhatsApp de contacto, biografía, servicios, fotografías, trabajos, enlaces y reseñas aprobadas.","Solicitudes privadas: necesidad, ubicación aproximada, contacto, estado y hasta los adjuntos permitidos.","Verificación y operación: comprobaciones, altas asistidas, reclamaciones, plan y acciones administrativas.","Datos técnicos: eventos de uso, fuente de visita, dispositivo, user-agent, cookies o almacenamiento local e IP anonimizada mediante hash."]},
    {title:"3. Perfiles públicos",paragraphs:["La información marcada como pública puede ser vista, compartida e indexada por buscadores cuando la ficha cumpla los criterios de publicación. Evita incluir domicilios particulares, documentos o información sensible.","Los perfiles de muestra se identifican como tales y no habilitan contacto. Las fichas suspendidas dejan de estar disponibles públicamente."]},
    {title:"4. Finalidades",items:["Crear y proteger cuentas; comprobar el celular y recuperar acceso cuando esté habilitado.","Publicar y administrar perfiles, negocios, servicios y trabajos.","Procesar solicitudes, favoritos, reclamaciones, reseñas y solicitudes de Pro.","Facilitar contacto por WhatsApp y medir visitas, fuentes y conversiones.","Prevenir abuso, investigar incidentes, moderar contenido y cumplir obligaciones legales.","Mejorar rendimiento, accesibilidad y experiencia de Tequit."]},
    {title:"5. Bases y decisiones del usuario",paragraphs:["Tratamos datos para prestar las funciones solicitadas, atender tu consentimiento, proteger intereses legítimos de seguridad y cumplir obligaciones aplicables. Puedes no proporcionar datos opcionales, aunque algunas funciones requieren celular y datos mínimos.","La aceptación registrada identifica la versión, momento, origen, user-agent limitado e IP anonimizada; no guardamos la IP cruda como evidencia legal."]},
    {title:"6. Proveedores y terceros",paragraphs:["Usamos Supabase para autenticación, base de datos y archivos; Vercel para alojamiento; Cloudflare para dominio, DNS y seguridad; y Bird para mensajería de verificación. Estos proveedores tratan datos conforme a sus contratos y ubicaciones de infraestructura.","WhatsApp y Meta son terceros independientes cuando abres conversaciones o recibes mensajes. Sus propios términos y políticas aplican. No vendemos datos personales ni los compartimos para publicidad de terceros."]},
    {title:"7. Solicitudes, adjuntos y acceso",paragraphs:["Los datos de una solicitud y sus archivos privados se limitan al cliente, destinatario y personal autorizado de Tequit según su función. Aplicamos controles de acceso y enlaces temporales cuando corresponde.","No podemos garantizar seguridad absoluta. Si detectamos un incidente relevante actuaremos para contenerlo y realizar las notificaciones exigibles."]},
    {title:"8. Conservación",paragraphs:["Conservamos la cuenta mientras permanezca activa y los datos operativos durante el tiempo necesario para prestar el servicio, resolver disputas, prevenir fraude y cumplir obligaciones. Los temporales de carga se eliminan después de validarse o expirar.","Al eliminar una cuenta despublicaremos o desvincularemos sus datos según corresponda. Evidencias de consentimiento, auditoría y seguridad podrán conservarse durante el plazo legal o defensivo necesario."]},
    {title:"9. Derechos ARCO y eliminación",paragraphs:[`Puedes solicitar acceso, rectificación, cancelación u oposición, revocar consentimiento cuando proceda, o pedir eliminación escribiendo a ${LEGAL_CONTACT}. Incluye información suficiente para identificar tu cuenta; podremos pedir una comprobación razonable de identidad.`,`Responderemos conforme a la legislación mexicana aplicable. Algunas solicitudes pueden limitarse cuando exista obligación legal, defensa de derechos o información de terceros.`]},
    {title:"10. Menores",paragraphs:["Tequit no está dirigido a menores de 18 años ni permite que creen cuentas. Si detectamos datos de un menor sin autorización válida, los eliminaremos y podremos cerrar la cuenta relacionada."]},
    {title:"11. Cookies y almacenamiento local",paragraphs:["Usamos cookies esenciales para sesión y seguridad, y almacenamiento local o de sesión para funciones como favoritos, preferencias o continuidad de registro. No usamos estos mecanismos para publicidad conductual en esta beta."]},
    {title:"12. Cambios y contacto",paragraphs:[`Publicaremos cada versión con su fecha de vigencia. Los cambios materiales podrán requerir una nueva aceptación sin reemplazar el historial anterior. Para dudas o solicitudes escribe a ${LEGAL_CONTACT}.`]}
  ]
};

export const legalDocuments={terms:termsDocument,privacy:privacyDocument} as const;
