import {notFound} from "next/navigation";
import {AdminShell} from "@/components/admin-shell";
import {AssistedInitial,AssistedOnboardingWizard} from "@/components/assisted-onboarding-wizard";
import {AssistedOnboardingActions} from "@/components/assisted-onboarding-actions";
import {requireRole} from "@/lib/auth";
import {createAdminClient} from "@/lib/supabase/admin";

export default async function ResumeAssistedPage({params}:{params:Promise<{id:string}>}){await requireRole(["admin"]);const{id}=await params;const admin=createAdminClient()!;const{data:onboarding}=await admin.from("assisted_onboardings").select("*").eq("id",id).maybeSingle();if(!onboarding)notFound();const entityId=onboarding.provider_id??onboarding.business_id;const kind=onboarding.kind as "provider"|"business";
  const [{data:canonical},{data:entity},{data:serviceRows},{data:areaRows},{data:verificationRows},{data:site},{data:mediaRows}]=await Promise.all([
    admin.from("canonical_services").select("id,name,service_categories(name)").eq("active",true).order("name"),
    kind==="provider"?admin.from("provider_profiles").select("name,phone,profession,zone,bio,slug,avatar_path").eq("id",entityId).single():admin.from("businesses").select("name,phone,zone,address,description,slug,logo_path,cover_path,service_categories(name)").eq("id",entityId).single(),
    admin.from(kind==="provider"?"provider_services":"business_services").select("canonical_service_id,title,description").eq(kind==="provider"?"provider_id":"business_id",entityId).order("created_at"),
    admin.from(kind==="provider"?"provider_service_areas":"business_service_areas").select("service_areas(name)").eq(kind==="provider"?"provider_id":"business_id",entityId),
    admin.from(kind==="provider"?"provider_verifications":"business_verifications").select("type,note").eq(kind==="provider"?"provider_id":"business_id",entityId),
    kind==="provider"?admin.from("provider_site_settings").select("headline,years_experience,cover_path").eq("provider_id",entityId).maybeSingle():Promise.resolve({data:null}),
    admin.from(kind==="provider"?"provider_media":"business_media").select("storage_path").eq(kind==="provider"?"provider_id":"business_id",entityId).order("created_at"),
  ]);
  if(!entity)notFound();const row=entity as unknown as {name:string;phone:string;profession?:string;zone:string;bio?:string;address?:string;description?:string;slug:string;avatar_path?:string|null;logo_path?:string|null;cover_path?:string|null;service_categories?:{name:string}[]};const storage=(bucket:string,path:string|null|undefined)=>path?`${process.env.NEXT_PUBLIC_SUPABASE_URL}/storage/v1/object/public/${bucket}/${path}`:undefined;const mediaBucket=kind==="provider"?"provider-work":"business-media";
  const initial:AssistedInitial={id:onboarding.id,entityId,slug:row.slug,status:onboarding.status,name:row.name,phone:row.phone,profession:kind==="provider"?row.profession??"":row.service_categories?.[0]?.name??"Servicios",zone:row.zone,address:row.address??"",source:onboarding.source,bio:kind==="provider"?row.bio??"":row.description??"",headline:site?.headline??"",yearsExperience:site?.years_experience??null,areas:(areaRows??[]).map(item=>item.service_areas?.[0]?.name).filter((value):value is string=>Boolean(value)),services:(serviceRows??[]).map(item=>({canonicalId:item.canonical_service_id,title:item.title,description:item.description})),verifications:(verificationRows??[]).map(item=>({type:item.type,note:item.note??"Confirmado durante el alta asistida"})),consentConfirmed:onboarding.consent_confirmed,consentNote:onboarding.consent_note??"",duplicateReviewed:onboarding.duplicate_reviewed,duplicateNote:onboarding.duplicate_note??"",media:{avatar:storage(kind==="provider"?"avatars":"business-media",kind==="provider"?row.avatar_path:row.logo_path),cover:storage(mediaBucket,kind==="provider"?site?.cover_path:row.cover_path),portfolio:(mediaRows??[]).map(item=>storage(mediaBucket,item.storage_path)).filter((value):value is string=>Boolean(value))}};
  const services=(canonical??[]).map(item=>({id:item.id,name:item.name,category:item.service_categories?.[0]?.name??"Servicios"}));return <AdminShell>{onboarding.status==="published"&&<AssistedOnboardingActions id={onboarding.id} status={onboarding.status} detail/>}<AssistedOnboardingWizard kind={kind} canonicalServices={services} initial={initial}/></AdminShell>;
}
